const js = require('@eslint/js');
const security = require('eslint-plugin-security');
const prettier = require('eslint-config-prettier');

module.exports = [
  js.configs.recommended,
  prettier,
  {
    plugins: { security },
    rules: {
      ...security.configs.recommended.rules,
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-var': 'warn',
      'prefer-const': 'warn',
      eqeqeq: ['warn', 'smart'],
    },
  },
  // Node.js files (configs, scripts)
  {
    files: ['*.js', 'scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'writable',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
      },
    },
  },
  // Node.js ESM (server)
  {
    files: ['site/server.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
  },
  // Background service worker (importScripts shares globals across files)
  {
    files: ['extension/background/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        chrome: 'readonly',
        ethers: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Uint8Array: 'readonly',
        BigInt: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        importScripts: 'readonly',
        self: 'readonly',
        globalThis: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        // shared/ modules
        MessageType: 'readonly',
        BroadcastEvent: 'readonly',
        NETWORKS: 'writable',
        DEFAULT_NETWORK_KEY: 'writable',
        // sw-security globals
        _swLog: 'readonly',
        _debugEnabled: 'writable',
        LOCK_ALARM: 'readonly',
        LOCK_DELAY_MIN_DEFAULT: 'readonly',
        LOCK_DELAY_OPTIONS: 'readonly',
        getLockDelayMin: 'readonly',
        DAPP_REQUEST_TTL_MS: 'readonly',
        MAX_CONNECTED_ORIGINS: 'readonly',
        CONNECTED_ORIGIN_TTL_MS: 'readonly',
        enforceConnectedOriginsLimits: 'readonly',
        getLockoutState: 'readonly',
        recordFailedAttempt: 'readonly',
        resetLockoutState: 'readonly',
        appendAuditLog: 'readonly',
        // sw-wallet globals
        ERC20_ABI: 'readonly',
        _walletsByAddress: 'readonly',
        _activeWalletAddress: 'writable',
        MAX_UNLOCKED_WALLETS: 'readonly',
        rememberUnlockedWallet: 'readonly',
        getActiveWallet: 'readonly',
        clearUnlockedWallets: 'readonly',
        getWalletForAddress: 'readonly',
        getActiveNetworkParams: 'readonly',
        ensureConnectedOriginHasAddress: 'readonly',
        toBigIntHex: 'readonly',
        // sw-rpc globals
        rpcResult: 'readonly',
        rpcError: 'readonly',
        proxyRpc: 'readonly',
        // sw-dapp globals
        isFromExtensionContext: 'readonly',
        isFromOurContentScript: 'readonly',
        POPUP_ONLY_MESSAGE_TYPES: 'readonly',
        CONTENT_SCRIPT_MESSAGE_TYPES: 'readonly',
        requestApproval: 'readonly',
        handleApprovalResponse: 'readonly',
        openApprovalWindow: 'readonly',
        dispatchDappMethod: 'readonly',
        _pendingApprovals: 'writable',
        crypto: 'readonly',
        // sw-broadcast globals
        broadcastToOrigin: 'readonly',
        broadcastToAllConnected: 'readonly',
        broadcastChainChanged: 'readonly',
        broadcastAccountsChanged: 'readonly',
        // sw-handlers globals
        handleMessage: 'readonly',
        handleDappRequest: 'readonly',
        // sw-wallet nonce manager (declared in sw-wallet.ts, shared via importScripts)
        getNextNonce: 'readonly',
        resetNonce: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-redeclare': 'off', // SW globals are shared via importScripts
    },
  },
  // Popup standalone scripts (non-module IIFE, e.g. error-boundary loaded via <script>)
  {
    files: ['extension/popup/error-boundary.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        chrome: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        location: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
      },
    },
  },
  // Popup entry & popup.js (ES modules bundled by esbuild)
  {
    files: ['extension/popup/popup.js', 'extension/popup/popup-entry.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        chrome: 'readonly',
        ethers: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Uint8Array: 'readonly',
        BigInt: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        MessageType: 'readonly',
        BroadcastEvent: 'readonly',
        globalThis: 'readonly',
        self: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLButtonElement: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        Clipboard: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        location: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        URLSearchParams: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  // Content scripts & inpage (non-module)
  {
    files: ['extension/content/**/*.js', 'extension/inpage/**/*.js', 'extension/network-config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        chrome: 'readonly',
        ethers: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Uint8Array: 'readonly',
        BigInt: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        MessageType: 'readonly',
        BroadcastEvent: 'readonly',
        globalThis: 'readonly',
        self: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLButtonElement: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        Clipboard: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        location: 'readonly',
        alert: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  // Popup ES modules (bundled by esbuild)
  {
    files: ['extension/popup/modules/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        chrome: 'readonly',
        ethers: 'readonly',
        console: 'readonly',
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Uint8Array: 'readonly',
        BigInt: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        MessageType: 'readonly',
        BroadcastEvent: 'readonly',
        globalThis: 'readonly',
        self: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLButtonElement: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        Clipboard: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        location: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  // Site JS
  {
    files: ['site/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        document: 'readonly',
        window: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        URL: 'readonly',
        location: 'readonly',
        alert: 'readonly',
        navigator: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        localStorage: 'readonly',
        history: 'readonly',
        clearTimeout: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  // E2E tests (relaxed: empty catch blocks are common in resilience tests)
  {
    files: ['tests/e2e/**/*.spec.js', 'tests/e2e/**/*.js'],
    rules: {
      'no-empty': 'off',
    },
  },
  // Test files
  {
    files: ['tests/**/*.js', 'tests/**/*.test.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        console: 'readonly',
        globalThis: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        document: 'readonly',
        window: 'readonly',
        BigInt: 'readonly',
        Uint8Array: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        require: 'readonly',
        module: 'readonly',
        chrome: 'readonly',
        navigator: 'readonly',
        alert: 'readonly',
        location: 'readonly',
        crypto: 'readonly',
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLButtonElement: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        CustomEvent: 'readonly',
        AbortController: 'readonly',
        __dirname: 'readonly',
        Response: 'readonly',
        getComputedStyle: 'readonly',
        clearInterval: 'readonly',
        setInterval: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-empty': 'off', // test mocks often have intentional empty blocks
    },
  },
  {
    ignores: [
      'extension/libs/**',
      'extension/popup/popup.bundle.js',
      'extension/shared/*.js', // generated from .ts by esbuild
      'extension/background/*.js', // generated from .ts by esbuild
      'node_modules/**',
      'test-results/**',
    ],
  },
];
