#!/usr/bin/env node
'use strict';

// ── SOVA Wallet — esbuild bundler ───────────────────────────────────────
// Bundles popup modules into a single popup.bundle.js for CSP compliance.
// ethers.umd.min.js stays external (loaded via separate <script> tag).
//
// Usage:
//   node scripts/build.js           — one-shot build
//   node scripts/build.js --watch   — watch mode for development

const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const ROOT = path.resolve(__dirname, '..');
const EXT = path.join(ROOT, 'extension');
const isWatch = process.argv.includes('--watch');

// ── Popup bundle ────────────────────────────────────────────────────────
// Entry point concatenates all IIFE modules in correct order, then popup.js.
// Since modules are IIFEs that self-register on globalThis, the entry file
// just needs to execute them in order — esbuild inlines each require.

const POPUP_ENTRY = path.join(EXT, 'popup', 'popup-entry.js');

// Generate entry file from popup.html script order (excluding ethers.umd)
function generatePopupEntry() {
  const html = fs.readFileSync(path.join(EXT, 'popup', 'popup.html'), 'utf8');
  const scriptRe = /<script\s+src="([^"]+)"><\/script>/g;
  const scripts = [];
  let m;
  while ((m = scriptRe.exec(html)) !== null) {
    const src = m[1];
    // Skip ethers (external), skip bundle itself
    if (src.includes('ethers.umd') || src.includes('.bundle.')) continue;
    scripts.push(src);
  }

  const lines = [
    '// Auto-generated by scripts/build.js — do not edit manually',
    '// Loads all popup IIFE modules in the correct order from popup.html',
    '',
  ];

  for (const src of scripts) {
    // Resolve relative to popup/ directory
    const resolved = src.startsWith('../')
      ? `../../extension/${src.replace('../', '')}`
      : `../../extension/popup/${src}`;
    lines.push(`require('${resolved}');`);
  }

  fs.writeFileSync(POPUP_ENTRY, lines.join('\n') + '\n');
  return scripts.length;
}

async function build() {
  const scriptCount = generatePopupEntry();
  console.log(`[build] Generated popup-entry.js with ${scriptCount} scripts`);

  const commonOptions = {
    bundle: true,
    format: 'iife',
    target: 'es2020',
    minify: !isWatch,
    sourcemap: isWatch ? 'inline' : false,
    logLevel: 'info',
  };

  // Popup bundle
  const popupCtx = await esbuild.context({
    ...commonOptions,
    entryPoints: [POPUP_ENTRY],
    outfile: path.join(EXT, 'popup', 'popup.bundle.js'),
    // ethers is loaded via <script> tag, available as global
    external: [],
    // ethers is already global — we just need the modules that use it
    define: {},
  });

  if (isWatch) {
    console.log('[build] Watching for changes...');
    await popupCtx.watch();
  } else {
    await popupCtx.rebuild();
    await popupCtx.dispose();

    // Report sizes
    const bundlePath = path.join(EXT, 'popup', 'popup.bundle.js');
    const stats = fs.statSync(bundlePath);
    const kb = (stats.size / 1024).toFixed(1);
    console.log(`[build] popup.bundle.js: ${kb} KB`);
  }
}

build().catch((err) => {
  console.error('[build] FAILED:', err.message);
  process.exit(1);
});
